using System;
using System.Drawing;
using System.IO;
using System.Security.Cryptography;
using System.Web.Script.Serialization;
using System.Windows.Forms;

namespace DeskBuddy {
 public class AdminSecret {public string Salt="",Hash="";}
 public static class AdminAccess {
  public static string FilePath=Path.Combine(Store.Root,"admin.json");
  public static bool Configured{get{return File.Exists(FilePath);}}
  static byte[] Hash(string password,byte[] salt){using(var derive=new Rfc2898DeriveBytes(password,salt,150000))return derive.GetBytes(32);}
  public static bool Verify(string password){if(!Configured)return false;var secret=new JavaScriptSerializer().Deserialize<AdminSecret>(File.ReadAllText(FilePath));byte[] expected=Convert.FromBase64String(secret.Hash),actual=Hash(password,Convert.FromBase64String(secret.Salt));int diff=expected.Length^actual.Length;for(int i=0;i<Math.Min(expected.Length,actual.Length);i++)diff|=expected[i]^actual[i];return diff==0;}
  public static void SetPassword(string password){if(password.Length<6)throw new Exception("비밀번호는 6자 이상 입력해주세요.");byte[] salt=new byte[32];using(var rng=RandomNumberGenerator.Create())rng.GetBytes(salt);var secret=new AdminSecret{Salt=Convert.ToBase64String(salt),Hash=Convert.ToBase64String(Hash(password,salt))};Directory.CreateDirectory(Path.GetDirectoryName(FilePath));string temp=FilePath+".tmp";File.WriteAllText(temp,new JavaScriptSerializer().Serialize(secret));if(File.Exists(FilePath))File.Replace(temp,FilePath,null);else File.Move(temp,FilePath);}
  public static void SetLevel(Data d,int level){if(level<1||level>100)throw new ArgumentOutOfRangeException("level");d.ExperienceAdjustment=(level-1)*100-Companions.NaturalExperience(d);}
  public static void Tests(){string previous=FilePath,dir=Path.Combine(Path.GetTempPath(),"DeskBuddy-admin-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);FilePath=Path.Combine(dir,"admin.json");try{SetPassword("test-password-one");if(!Verify("test-password-one")||Verify("wrong-password")||File.ReadAllText(FilePath).Contains("test-password-one"))throw new Exception("Admin password protection");SetPassword("test-password-two");if(Verify("test-password-one")||!Verify("test-password-two"))throw new Exception("Password change");var d=new Data{Completed=2,FocusMinutes=10};SetLevel(d,2);if(Companions.Level(d)!=2||d.Completed!=2||d.FocusMinutes!=10)throw new Exception("Admin level adjustment");string error;if(!Companions.Adopt(d,out error))throw new Exception("Admin pet unlock");var copy=new JavaScriptSerializer().Deserialize<Data>(new JavaScriptSerializer().Serialize(d));if(Companions.Level(copy)!=2)throw new Exception("Admin level persistence");d.ExperienceAdjustment=0;if(Companions.Level(d)!=1||Companions.Current(d)!=null)throw new Exception("Natural level restore hides pet");int coins=d.Coins;if(Companions.Care(d,false,AppClock.Now,out error)||d.Coins!=coins)throw new Exception("Locked pet care");using(var image=new Bitmap(64,64))using(var g=Graphics.FromImage(image)){g.Clear(Color.Transparent);Companions.Draw(g,new Rectangle(0,0,64,64),d,0);for(int y=0;y<64;y++)for(int x=0;x<64;x++)if(image.GetPixel(x,y).A!=0)throw new Exception("Locked pet drawing");}SetLevel(d,2);if(Companions.Current(d)==null||Companions.Adopt(d,out error))throw new Exception("Pet resumes without duplicate adoption");}finally{FilePath=previous;foreach(string file in Directory.GetFiles(dir))File.Delete(file);Directory.Delete(dir);}}
 }
 public class AdminForm:Form {
  bool authenticated;Label status;TextBox password,confirm;NumericUpDown level;
  public AdminForm(){Text="DeskBuddy 관리자 설정";Icon=AppIdentity.Icon;ClientSize=new Size(590,390);StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;AutoScaleMode=AutoScaleMode.None;BackColor=Theme.Bg;Login();}
  void Base(string title){Controls.Clear();Controls.Add(Theme.Label(title,24,20,540,35,14));status=Theme.Label("",24,326,540,45,10,Theme.Muted);Controls.Add(status);}
  TextBox Secret(int y){var box=Theme.Input("",190,y,365);box.UseSystemPasswordChar=true;box.MaxLength=128;Controls.Add(box);return box;}
  void Login(){bool setup=!AdminAccess.Configured;Base(setup?"관리자 비밀번호 만들기":"관리자 로그인");Controls.Add(Theme.Label(setup?"이 PC에서 사용할 비밀번호를 직접 정해주세요.":"설정한 관리자 비밀번호를 입력해주세요.",24,68,540,26,10));Controls.Add(Theme.Label("비밀번호",24,123,150,28));password=Secret(120);if(setup){Controls.Add(Theme.Label("다시 입력",24,173,150,28));confirm=Secret(170);}Controls.Add(Theme.Button(setup?"설정하고 로그인":"로그인",190,232,365,45,(s,e)=>{try{if(setup){if(password.Text!=confirm.Text)throw new Exception("비밀번호가 서로 달라요.");AdminAccess.SetPassword(password.Text);}else if(!AdminAccess.Verify(password.Text))throw new Exception("비밀번호가 맞지 않아요.");authenticated=true;password.Clear();if(confirm!=null)confirm.Clear();Panel();}catch(Exception ex){status.Text=ex.Message;}},true));Controls.Add(Theme.Label("관리자 설정은 이 PC에서만 사용합니다.",24,290,540,25,10,Theme.Muted));}
  void Panel(){if(!authenticated)return;Base("관리자 · 레벨 조정");Controls.Add(Theme.Label("업무·집중 기록을 유지한 채 레벨만 조정해요.",24,68,540,28,10));Controls.Add(Theme.Label("레벨 (1~100)",24,123,170,28));level=new NumericUpDown{Location=new Point(210,120),Size=new Size(130,32),Minimum=1,Maximum=100,Value=Math.Min(100,Companions.Level(Store.State)),Font=Theme.Font(11)};Controls.Add(level);Controls.Add(Theme.Button("레벨 적용",355,116,200,42,(s,e)=>{int old=Store.State.ExperienceAdjustment;AdminAccess.SetLevel(Store.State,(int)level.Value);if(!Store.Save()){Store.State.ExperienceAdjustment=old;status.Text="저장하지 못했어요.";return;}status.Text="레벨 "+Companions.Level(Store.State)+" 적용 완료! 펫 키우기를 열어보세요.";},true));Controls.Add(Theme.Button("원래 경험치로 돌아가기",24,187,531,42,(s,e)=>{int old=Store.State.ExperienceAdjustment;Store.State.ExperienceAdjustment=0;if(!Store.Save()){Store.State.ExperienceAdjustment=old;return;}level.Value=Math.Min(100,Companions.Level(Store.State));status.Text="업무와 집중으로 얻은 원래 레벨로 돌아왔어요.";}));Controls.Add(Theme.Button("비밀번호 변경",24,245,255,42,(s,e)=>ChangePassword()));Controls.Add(Theme.Button("로그아웃",300,245,255,42,(s,e)=>{authenticated=false;Login();}));status.Text="창을 닫으면 자동으로 로그아웃됩니다.";}
  void ChangePassword(){if(!authenticated)return;Base("관리자 비밀번호 변경");Controls.Add(Theme.Label("새 비밀번호",24,123,150,28));password=Secret(120);Controls.Add(Theme.Label("다시 입력",24,173,150,28));confirm=Secret(170);Controls.Add(Theme.Button("변경",190,232,365,45,(s,e)=>{try{if(password.Text!=confirm.Text)throw new Exception("비밀번호가 서로 달라요.");AdminAccess.SetPassword(password.Text);password.Clear();confirm.Clear();Panel();status.Text="비밀번호를 변경했어요.";}catch(Exception ex){status.Text=ex.Message;}},true));Controls.Add(Theme.Button("돌아가기",24,232,145,45,(s,e)=>Panel()));}
 }
}
