using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Windows.Forms;
using System.Web.Script.Serialization;

namespace DeskBuddy {
 public class LittlePet {public int Growth,Bond;public string LastCare="",LastPlay="";}
 public static class Companions {
  public static int SizeFor(int mainSize){return Math.Max(1,(int)Math.Round(mainSize/3.0));}
  public static int NaturalExperience(Data d){return Math.Max(0,d.Completed*20+d.FocusMinutes+Math.Max(0,d.InteractionExperience));}
  public static int Experience(Data d){return Math.Max(0,NaturalExperience(d)+d.ExperienceAdjustment);}
  public static bool RewardInteraction(Data d,DateTime now){if(now<AppClock.Decode(d.LastInteractionLocal,DateTime.MinValue).AddSeconds(30))return false;d.InteractionExperience+=5;d.LastInteractionLocal=AppClock.Encode(now);return true;}
  public static int Level(Data d){return 1+Experience(d)/100;}
  public static string Key(Data d){return String.IsNullOrEmpty(d.ImagePath)?CharacterLibrary.Default:d.ImagePath;}
  public static LittlePet Current(Data d){if(Level(d)<2)return null;if(d.Companions==null)d.Companions=new Dictionary<string,LittlePet>();LittlePet p;return d.Companions.TryGetValue(Key(d),out p)?p:null;}
  public static string Stage(LittlePet p){return p==null?"입양 전":p.Growth<3?"알":p.Growth<10?"아기 펫":"다 자란 펫";}
  public static bool Adopt(Data d,out string error){error="";if(Level(d)<2){error="레벨 2부터 알을 입양할 수 있어요.";return false;}if(Current(d)!=null){error="이미 함께 키우는 펫이 있어요.";return false;}d.Companions[Key(d)]=new LittlePet();return true;}
  public static bool Care(Data d,bool food,DateTime now,out string error){error="";if(Level(d)<2){error="레벨 2부터 펫을 돌볼 수 있어요.";return false;}var p=Current(d);if(p==null){error="먼저 알을 입양해주세요.";return false;}if(now<AppClock.Decode(p.LastCare,DateTime.MinValue).AddMinutes(1)){error="조금 쉬었다가 돌봐주세요. 돌봄은 1분마다 가능해요.";return false;}int cost=food?8:5;if(d.Coins<cost){error="코인이 부족해요.";return false;}d.Coins-=cost;p.Growth=Math.Min(10,p.Growth+1);p.Bond++;p.LastCare=AppClock.Encode(now);return true;}
  public static void Draw(Graphics g,Rectangle box,Data d,int frame){var p=Current(d);if(p==null)return;var saved=g.Save();float unit=Math.Min(box.Width,box.Height)/32f;g.TranslateTransform(box.X+(box.Width-32*unit)/2,box.Y+(box.Height-32*unit)/2+(frame/6%2)*unit);g.ScaleTransform(unit,unit);
   Action<Color,int,int,int,int> r=(c,x,y,w,h)=>{using(var b=new SolidBrush(c))g.FillRectangle(b,x,y,w,h);};
   Color ink=Color.FromArgb(42,39,38),white=Color.FromArgb(255,253,246),gold=Color.FromArgb(255,203,70);
   string key=Key(d);bool bird=key.EndsWith("tae_ch",StringComparison.Ordinal);Color body=bird?white:key.EndsWith("jihyun_ch",StringComparison.Ordinal)?Color.FromArgb(185,145,211):key.EndsWith("jimin_ch",StringComparison.Ordinal)?Color.FromArgb(249,150,171):key.EndsWith("rita_ch",StringComparison.Ordinal)?Color.FromArgb(230,189,123):white;
   if(p.Growth>=3&&CompanionSprites.Draw(g,key,p.Growth<10)){g.Restore(saved);return;}
   if(p.Growth>=10&&key.EndsWith("jiyoung_ch",StringComparison.Ordinal)){DrawWoodstock(g);g.Restore(saved);return;}
   if(p.Growth<3){string[] egg={"............","....####....","...#wwww#...","..#wwwwww#..","..#wwawww#..",".#wwaaawww#.",".#wwwwwwww#.","#wwwwwwawww#","#wwwwwaaaww#","#wwwwwwwwww#",".#wwwwwwww#.","..########.."};for(int y=0;y<egg.Length;y++)for(int x=0;x<egg[y].Length;x++){char c=egg[y][x];if(c!='.')r(c=='#'?ink:c=='a'?body==white?gold:body:white,4+x*2,5+y*2,2,2);}if(p.Growth==2){r(ink,15,6,2,4);r(ink,13,10,2,2);r(ink,15,12,2,4);}}
   else {int offset=0;if(p.Growth<10){g.TranslateTransform(4,7);g.ScaleTransform(0.75f,0.75f);}int top=3;int[] edge={10,7,5,4,3,2,2,1,1,1,1,1,1,1,1,1,1,2,2,3,4,5,6,8,10};for(int y=top;y<28;y++){int inset=edge[y-top];r(ink,inset,y,32-2*inset,1);if(y>top&&y<27)r(body,inset+1,y,30-2*inset,1);}r(ink,9,11+offset,3,3);r(ink,21,11+offset,3,3);r(white,10,11+offset,1,1);r(white,22,11+offset,1,1);r(white,9,13+offset,1,1);r(white,21,13+offset,1,1);if(bird){r(ink,13,15+offset,7,3);r(gold,14,15+offset,5,2);r(ink,7,27,4,3);r(ink,23,27,4,3);r(gold,8,28,2,1);r(gold,24,28,2,1);}else{r(ink,15,16,3,2);r(ink,12,20,2,1);r(ink,14,21,6,1);if(key.EndsWith("jihyun_ch",StringComparison.Ordinal)){r(body,13,15,7,4);r(ink,13,20,2,1);r(ink,15,21,4,1);r(ink,19,20,2,1);r(ink,2,26,28,4);r(body,3,25,26,4);r(body,5,28,5,3);r(body,15,28,5,3);r(body,24,28,5,3);}else if(key.EndsWith("jimin_ch",StringComparison.Ordinal)){r(ink,4,1,6,6);r(ink,23,1,6,6);r(body,5,2,4,5);r(body,24,2,4,5);r(Color.FromArgb(115,55,80),13,15,7,4);r(white,14,22,5,3);r(Color.FromArgb(241,109,143),5,17,5,3);r(Color.FromArgb(241,109,143),24,17,4,3);}else if(key.EndsWith("rita_ch",StringComparison.Ordinal)){r(ink,4,0,7,7);r(ink,22,0,7,7);r(body,5,1,5,6);r(body,23,1,5,6);r(Color.FromArgb(236,165,166),6,2,3,3);r(Color.FromArgb(236,165,166),24,2,3,3);r(white,3,17,7,7);r(white,23,17,6,7);r(gold,12,23,9,5);r(body,9,24,4,3);r(body,21,24,3,3);}else{bool spotted=key.EndsWith("jiyoung_ch",StringComparison.Ordinal);r(ink,1,7,5,12);r(ink,26,7,5,12);r(spotted?ink:white,2,8,3,10);r(white,27,8,3,10);r(ink,14,16,5,3);r(body,9,27,5,3);r(body,21,27,5,3);if(spotted){r(ink,8,10,6,5);r(white,10,11,1,1);r(Color.FromArgb(231,66,78),10,24,13,2);}}}if(p.Growth>=10&&bird){r(gold,0,1,2,5);r(gold,29,3,2,4);r(gold,2,3,3,2);r(gold,27,1,3,2);}}
   g.Restore(saved);
  }
  static void DrawWoodstock(Graphics g){Color yellow=Color.FromArgb(255,217,0);using(var b=new SolidBrush(yellow))using(var pen=new Pen(Color.FromArgb(24,24,20),1.7f)){pen.LineJoin=System.Drawing.Drawing2D.LineJoin.Miter;Point[] tail={new Point(20,22),new Point(24,20),new Point(25,15),new Point(28,15),new Point(29,13),new Point(31,16),new Point(28,18),new Point(26,18),new Point(24,23)};g.FillPolygon(b,tail);g.DrawPolygon(pen,tail);Point[] body={new Point(13,15),new Point(14,18),new Point(18,17),new Point(20,20),new Point(19,23),new Point(23,24),new Point(23,29),new Point(21,31),new Point(18,31),new Point(18,27),new Point(15,26),new Point(13,26),new Point(11,24),new Point(11,20),new Point(8,20),new Point(8,18)};g.FillPolygon(b,body);g.DrawPolygon(pen,body);Point[] head={new Point(3,10),new Point(6,9),new Point(7,7),new Point(6,4),new Point(4,3),new Point(2,5),new Point(3,2),new Point(6,2),new Point(8,4),new Point(9,4),new Point(8,1),new Point(9,0),new Point(11,2),new Point(13,3),new Point(15,3),new Point(16,1),new Point(17,1),new Point(17,6),new Point(19,5),new Point(22,4),new Point(24,5),new Point(26,7),new Point(27,8),new Point(25,9),new Point(26,11),new Point(24,13),new Point(23,15),new Point(21,17),new Point(18,19),new Point(15,19),new Point(12,17),new Point(8,17),new Point(4,17),new Point(1,16),new Point(0,13)};g.FillPolygon(b,head);g.DrawPolygon(pen,head);g.DrawLine(pen,8,9,9,11);g.DrawLine(pen,22,10,24,12);g.DrawLines(pen,new[]{new Point(17,14),new Point(16,16),new Point(13,17)});g.DrawLines(pen,new[]{new Point(16,19),new Point(18,20),new Point(16,22)});g.DrawLine(pen,20,25,19,29);g.DrawLines(pen,new[]{new Point(26,27),new Point(27,28),new Point(27,30),new Point(25,31)});}}
  public static void Tests(){var interaction=new Data();DateTime at=new DateTime(2026,10,7,12,0,0);if(!RewardInteraction(interaction,at)||RewardInteraction(interaction,at.AddSeconds(29))||!RewardInteraction(interaction,at.AddSeconds(30))||Experience(interaction)!=10)throw new Exception("Interaction XP and cooldown");var saved=new JavaScriptSerializer().Deserialize<Data>(new JavaScriptSerializer().Serialize(interaction));if(RewardInteraction(saved,at.AddSeconds(31))||Experience(saved)!=10)throw new Exception("Interaction XP persistence");AdminAccess.SetLevel(interaction,3);if(Level(interaction)!=3)throw new Exception("Admin level includes interaction XP");interaction.ExperienceAdjustment=0;if(Experience(interaction)!=10)throw new Exception("Natural interaction XP restore");foreach(int size in new[]{40,84,140,320})if(SizeFor(size)>=size||Math.Abs(SizeFor(size)-size/3.0)>0.51)throw new Exception("Companion one-third size");string error;var d=new Data{Coins=100};if(Adopt(d,out error))throw new Exception("Level gate");d.Completed=5;if(!Adopt(d,out error)||Adopt(d,out error))throw new Exception("Adoption");DateTime now=AppClock.Now;for(int i=0;i<10;i++){if(!Care(d,false,now.AddMinutes(i),out error))throw new Exception("Growth");if(Care(d,true,now.AddMinutes(i),out error))throw new Exception("Care cooldown");}if(Current(d).Growth!=10||d.Coins!=50)throw new Exception("Adult and cost");d.ImagePath=CharacterLibrary.Bundled.Last();if(Current(d)!=null||!Adopt(d,out error))throw new Exception("Independent pets");d.Coins=0;if(Care(d,true,now,out error)||Current(d).Growth!=0)throw new Exception("Funds");var copy=new JavaScriptSerializer().Deserialize<Data>(new JavaScriptSerializer().Serialize(d));if(copy.Companions.Count!=2)throw new Exception("Pet persistence");}
 }
 public class CompanionPortrait:Control {public CompanionPortrait(){DoubleBuffered=true;}protected override void OnPaint(PaintEventArgs e){Companions.Draw(e.Graphics,ClientRectangle,Store.State,0);}}
 public static class CompanionUiTests {
  static IEnumerable<Control> All(Control root){foreach(Control c in root.Controls){yield return c;foreach(var child in All(c))yield return child;}}
  static Button Button(Form f,string text){return All(f).OfType<Button>().First(b=>b.Text==text);}
  static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
  static void Capture(Form f,string name){string dir=System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"preview");System.IO.Directory.CreateDirectory(dir);using(var b=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(b,new Rectangle(Point.Empty,b.Size));b.Save(System.IO.Path.Combine(dir,name+".png"));}}
  public static int Execute(){string oldPath=Store.FilePath;Data old=Store.State;string temp=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"DeskBuddy-companion-"+Guid.NewGuid().ToString("N"));System.IO.Directory.CreateDirectory(temp);Store.FilePath=System.IO.Path.Combine(temp,"data.json");Store.State=new Data{Coins=200,PetName="찌오",ImagePath=CharacterLibrary.Bundled.Last()};PetArt.LoadCustom(Store.State.ImagePath);PetArt.SetScheduleImage("");
   try{Companions.Tests();using(var pet=new PetForm())using(var form=new MainForm(pet)){form.Location=new Point(-2200,-1200);form.Show();form.Navigate("펫 키우기");Check(!Button(form,"알 입양하기").Enabled,"Level gate UI");Store.State.Completed=5;form.RefreshPage();Button(form,"알 입양하기").PerformClick();Check(Companions.Current(Store.State)!=null,"Adopt UI");Capture(form,"companion-egg");Button(form,"알 보살피기 5 G").PerformClick();Check(Store.State.Coins==195&&Companions.Current(Store.State).Growth==1,"Care UI cost");string error;for(int i=1;i<10;i++){Companions.Current(Store.State).LastCare=AppClock.Encode(AppClock.Now.AddMinutes(-2));Check(Companions.Care(Store.State,false,AppClock.Now,out error),"Care growth");if(i==2){form.RefreshPage();Capture(form,"companion-baby");}}form.RefreshPage();Capture(form,"companion-adult");pet.ApplyPetSize();using(var image=pet.RenderSnapshot())image.Save(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"preview","companion-desktop.png"));
    form.Navigate("나의 캐릭터");var slider=All(form).OfType<PixelSizeSlider>().First(x=>x.Maximum==160);slider.Value=160;Check(Store.State.BubbleScale==160&&pet.Height==132+Store.State.PetSize,"Bubble size UI");using(var image=pet.RenderSnapshot())image.Save(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"preview","bubble-large.png"));Store.Save();Store.State=new Data();Store.Load();Check(Store.State.BubbleScale==160&&Companions.Current(Store.State).Growth==10,"Settings and growth persistence");slider.Value=60;Check(pet.Height==62+Store.State.PetSize,"Small bubble size");Capture(form,"companion-settings");using(var preview=new SizePreviewForm(pet)){preview.StartPosition=FormStartPosition.Manual;preview.Location=new Point(-2200,-1200);preview.Show(form);var controls=All(preview).OfType<PixelSizeSlider>().ToArray();controls[0].Value=320;controls[1].Value=160;Check(Store.State.PetSize==320&&Store.State.BubbleScale==160,"Preview sliders apply");Capture(preview,"size-preview");var canvas=All(preview).OfType<SizePreviewCanvas>().Single();using(var image=new Bitmap(canvas.Width,canvas.Height)){canvas.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));Check(image.GetPixel(canvas.Width/2,canvas.Height/2)!=Theme.Light,"Preview image visible");}controls[0].Value=140;controls[1].Value=100;}}
    System.IO.File.WriteAllText(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"companion-validation.txt"),"PASS: level gate, adoption UI, egg/baby/adult growth, care costs and cooldown, independent character pets, save/reload, adjustable bubble layout and settings persistence.");return 0;
   }catch(Exception ex){System.IO.File.WriteAllText(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"companion-validation.txt"),"FAIL: "+ex);return 1;}
   finally{Store.FilePath=oldPath;Store.State=old;foreach(string file in System.IO.Directory.GetFiles(temp))System.IO.File.Delete(file);System.IO.Directory.Delete(temp);}
  }
 }
}
