using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Script.Serialization;
using System.Windows.Forms;
namespace DeskBuddy {
 public class MemoNote {public string Id=Guid.NewGuid().ToString("N"),Text="";public bool Pinned;}
 public static class StickyMemos {
  public const int MaxPinned=3;
  public static void Normalize(Data data){if(data.Memos==null)data.Memos=new List<MemoNote>();data.Memos.RemoveAll(m=>m==null);int count=0;foreach(var note in data.Memos){if(String.IsNullOrEmpty(note.Id))note.Id=Guid.NewGuid().ToString("N");if(note.Text==null)note.Text="";if(note.Pinned&&++count>MaxPinned)note.Pinned=false;}}
  public static List<MemoNote> Pinned(Data data){return (data.Memos??new List<MemoNote>()).Where(m=>m!=null&&m.Pinned).Take(MaxPinned).ToList();}
  public static bool Put(Data data,string id,string text,bool pinned,out string error){error="";Normalize(data);if(String.IsNullOrWhiteSpace(text)){error="메모 내용을 입력해주세요.";return false;}if(text.Length>2000){error="메모는 2,000자까지 쓸 수 있어요.";return false;}var note=data.Memos.FirstOrDefault(m=>m.Id==id);if(pinned&&data.Memos.Count(m=>m.Pinned&&m!=note)>=MaxPinned){error="머리 위에는 메모를 최대 3개까지 띄울 수 있어요.\n다른 메모의 머리 위 표시를 먼저 꺼주세요.";return false;}if(note==null){note=new MemoNote();data.Memos.Add(note);}note.Text=text.Trim();note.Pinned=pinned;return true;}
  public static int NoteHeight(Data data,int available){int count=Pinned(data).Count;return count==0?0:Math.Max(32,Math.Min(76,(available-8)/count-6));}
  public static int Space(Data data,int available){int count=Pinned(data).Count;return count==0?0:(NoteHeight(data,available)+6)*count+8;}
  public static void Draw(Graphics g,int width,int top,Data data,int available){var notes=Pinned(data);int height=NoteHeight(data,available);Color[] colors={Color.FromArgb(255,235,148),Color.FromArgb(255,205,215),Color.FromArgb(191,228,241)};for(int i=0;i<notes.Count;i++){var box=new Rectangle((width-252)/2,top+8+i*(height+6),252,height);Theme.Frame(g,box,colors[i]);using(var font=Theme.PixelFont(10))Theme.Text(g,"MEMO "+(i+1),font,Theme.Muted,new Rectangle(box.X+10,box.Y+5,100,12));using(var brush=new SolidBrush(ControlPaint.Light(colors[i])))g.FillPolygon(brush,new[]{new Point(box.Right-18,box.Top+4),new Point(box.Right-4,box.Top+18),new Point(box.Right-18,box.Top+18)});using(var font=Theme.PixelFont(height<48?12:14))using(var brush=new SolidBrush(Theme.Ink))using(var format=new StringFormat(StringFormatFlags.LineLimit)){format.Trimming=StringTrimming.EllipsisWord;g.DrawString(notes[i].Text,font,brush,new Rectangle(box.X+10,box.Y+20,box.Width-20,box.Height-24),format);}}}
  public static void Tests(){var d=new Data();string error;for(int i=0;i<3;i++)if(!Put(d,null,"메모 "+i,true,out error))throw new Exception("Memo pin");if(Put(d,null,"네 번째",true,out error)||d.Memos.Count!=3)throw new Exception("Memo limit");if(!Put(d,null,"보관한 메모",false,out error)||d.Memos.Count!=4)throw new Exception("Memo archive");if(!Put(d,d.Memos[0].Id,"수정한 메모",true,out error)||d.Memos.Count!=4)throw new Exception("Memo edit");if(Put(d,null," ",false,out error))throw new Exception("Blank memo");d.Memos[0].Pinned=false;if(!Put(d,d.Memos[3].Id,"보관한 메모",true,out error)||Pinned(d).Count!=3)throw new Exception("Memo unpin");var copy=new JavaScriptSerializer().Deserialize<Data>(new JavaScriptSerializer().Serialize(d));if(Pinned(copy).Count!=3||copy.Memos.Count!=4)throw new Exception("Memo persistence");}
 }
 public class StickyMemoForm:Form {
  PetForm pet;ListBox list;TextBox text;CheckBox pinned;Label hint;string selectedId;bool loading;
  public StickyMemoForm(PetForm owner){pet=owner;Text="DeskBuddy · 메모 관리";Icon=AppIdentity.Icon;ClientSize=new Size(800,562);AutoScaleMode=AutoScaleMode.None;StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;BackColor=Theme.Bg;
   Controls.Add(Theme.Label("STICKY MEMO / 나의 메모",20,12,750,40,22));Controls.Add(Theme.Label("메모는 여러 개 보관하고, 머리 위에는 최대 3개까지 표시해요.",20,60,760,28,10,Theme.Muted));
   list=new ListBox{Location=new Point(20,103),Size=new Size(246,352),Font=Theme.Font(10),BackColor=Theme.Cream,BorderStyle=BorderStyle.FixedSingle,DrawMode=DrawMode.OwnerDrawFixed,ItemHeight=56};Controls.Add(list);list.DrawItem+=(s,e)=>{if(e.Index<0)return;var memo=(MemoNote)list.Items[e.Index];Theme.Fill(e.Graphics,(e.State&DrawItemState.Selected)!=0?Theme.Gold:Theme.Cream,e.Bounds.X,e.Bounds.Y,e.Bounds.Width,e.Bounds.Height);using(var format=new StringFormat(StringFormatFlags.NoWrap)){format.Trimming=StringTrimming.EllipsisCharacter;using(var brush=new SolidBrush(Theme.Ink))e.Graphics.DrawString(memo.Text.Replace("\r"," ").Replace("\n"," "),list.Font,brush,new Rectangle(8,e.Bounds.Y+6,e.Bounds.Width-16,23),format);}Theme.Text(e.Graphics,memo.Pinned?"머리 위에 표시 중":"보관 중",list.Font,Theme.Muted,new Rectangle(8,e.Bounds.Y+30,e.Bounds.Width-16,22));};list.SelectedIndexChanged+=(s,e)=>LoadSelection();
   text=new TextBox{Location=new Point(284,103),Size=new Size(496,302),Multiline=true,AcceptsReturn=true,ScrollBars=ScrollBars.Vertical,MaxLength=2000,Font=Theme.Font(10),BackColor=Theme.Cream,ForeColor=Theme.Ink};Controls.Add(text);
   pinned=new CheckBox{Text="캐릭터 머리 위에 표시",Location=new Point(284,418),Size=new Size(360,30),Font=Theme.Font(10),ForeColor=Theme.Ink};Controls.Add(pinned);
   hint=Theme.Label("",284,458,496,32,10,Theme.Muted);Controls.Add(hint);
   Controls.Add(Theme.Button("+ 새 메모",20,472,246,42,(s,e)=>{if(!Discard())return;loading=true;list.ClearSelected();selectedId=null;loading=false;text.Clear();pinned.Checked=StickyMemos.Pinned(Store.State).Count<3;text.Focus();}));
   Controls.Add(Theme.Button("메모 저장",284,502,240,42,(s,e)=>SaveCurrent(),true));Controls.Add(Theme.Button("선택 메모 삭제",540,502,240,42,(s,e)=>DeleteCurrent()));
   text.TextChanged+=(s,e)=>{if(!loading)hint.Text="저장을 누르면 바탕화면에도 바로 적용돼요.";};Reload(null);FormClosing+=(s,e)=>{if(!Discard())e.Cancel=true;};
  }
  bool Dirty(){var note=Store.State.Memos.FirstOrDefault(m=>m.Id==selectedId);return note==null?text.Text.Length>0:text.Text.Replace("\r\n","\n")!=note.Text.Replace("\r\n","\n")||pinned.Checked!=note.Pinned;}
  bool Discard(){return !Dirty()||GameAlert.Show("저장하지 않은 메모 변경을 버릴까요?","메모 관리",MessageBoxButtons.YesNo)==DialogResult.Yes;}
  void LoadSelection(){if(loading)return;var next=list.SelectedItem as MemoNote;if(!Discard()){loading=true;list.SelectedItem=Store.State.Memos.FirstOrDefault(m=>m.Id==selectedId);loading=false;return;}loading=true;selectedId=next==null?null:next.Id;text.Text=next==null?"":next.Text.Replace("\r\n","\n").Replace("\n","\r\n");pinned.Checked=next!=null&&next.Pinned;loading=false;UpdateHint();}
  void Reload(string id){StickyMemos.Normalize(Store.State);loading=true;list.Items.Clear();foreach(var note in Store.State.Memos)list.Items.Add(note);var selected=Store.State.Memos.FirstOrDefault(m=>m.Id==id);list.SelectedItem=selected;selectedId=selected==null?null:selected.Id;text.Text=selected==null?"":selected.Text.Replace("\r\n","\n").Replace("\n","\r\n");pinned.Checked=selected!=null&&selected.Pinned;loading=false;UpdateHint();}
  void UpdateHint(){hint.Text="머리 위 표시 "+StickyMemos.Pinned(Store.State).Count+" / 3 · 보관한 메모 "+Store.State.Memos.Count+"개";}
  void SaveCurrent(){var serializer=new JavaScriptSerializer();string before=serializer.Serialize(Store.State.Memos);string error;int count=Store.State.Memos.Count;if(!StickyMemos.Put(Store.State,selectedId,text.Text,pinned.Checked,out error)){GameAlert.Show(error,"메모 저장");return;}string id=selectedId??Store.State.Memos[count].Id;if(!Store.Save()){Store.State.Memos=serializer.Deserialize<List<MemoNote>>(before);return;}pet.ApplyPetSize();Reload(id);}
  void DeleteCurrent(){if(selectedId==null)return;if(GameAlert.Show("선택한 메모를 삭제할까요?","메모 삭제",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;var previous=Store.State.Memos.ToList();Store.State.Memos.RemoveAll(m=>m.Id==selectedId);if(!Store.Save()){Store.State.Memos=previous;return;}pet.ApplyPetSize();Reload(null);}
  public static int TestUi(){var previous=Store.State;string oldPath=Store.FilePath;string temp=Path.Combine(Path.GetTempPath(),"DeskBuddy-memos-"+Guid.NewGuid());Directory.CreateDirectory(temp);Store.FilePath=Path.Combine(temp,"data.json");try{TestsForUi();File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"memo-validation.txt"),"PASS: max 3 pinned, multiple stored memos, edit/unpin, JSON persistence, settings UI save, separate speech/memo/timer rendering, small-screen layout.");return 0;}catch(Exception ex){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"memo-validation.txt"),"FAIL: "+ex);return 1;}finally{Store.State=previous;Store.FilePath=oldPath;Directory.Delete(temp,true);}}
  static void TestsForUi(){StickyMemos.Tests();Store.State=new Data{FocusEnd=AppClock.Now.AddMinutes(24),PetSize=140};string error;foreach(string caption in new[]{"오늘은 물 많이 마시기!","회의 전에 자료 정리하기\n끝나면 잠깐 스트레칭","내일 준비물: 충전기, 노트북"})StickyMemos.Put(Store.State,null,caption,true,out error);
   using(var pet=new PetForm())using(var form=new StickyMemoForm(pet)){form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-2200,-1200);form.Show();form.Reload(Store.State.Memos[0].Id);form.text.Text="오늘은 물 많이 마시기! 수정";form.SaveCurrent();if(Store.State.Memos.Count!=3||!Store.State.Memos[0].Text.EndsWith("수정"))throw new Exception("Memo UI save");using(var image=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(image,new Rectangle(Point.Empty,image.Size));image.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"memo-settings-preview.png"));}using(var image=pet.RenderSnapshot(true))image.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"memo-desktop-preview.png"));int space=StickyMemos.Space(Store.State,168);if(space>176)throw new Exception("Memo layout budget");pet.Say("일정 시간이 됐어요!\n회의 준비해주세요.",false);using(var active=pet.RenderSnapshot()){int expected=(12+70)+StickyMemos.Space(Store.State,pet.MemoAvailable)+48+140+8;if(active.Height!=expected)throw new Exception("Memo layout overlap");}}
  }
 }
}
